version: '3.7'

services:
  db:
    image: postgres:11
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: currency_converter
      POSTGRES_HOST: db
    ports:
      - 5432:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: ./out/main
    volumes:
      - .:/app 
    ports:
      - 4000:4000 
    depends_on:
      - db

volumes: 
  postgres_data: